# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "D:\\git_pro2\\webapi"
      dockerfile: "webapi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/webapi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\wcz\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\git_pro2\\webapi\\webapi:/app:rw"
    - "D:\\git_pro2\\webapi:/src:rw"
    working_dir: "/app"
