services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
      - "5000:5001"  #Access port 5000, port 5001 inside the container
    environment:
      - ASPNETCORE_URLS=http://+:5001